"""
Legal tools — executed only through the Executor after PolicyEngine approval.
Each tool receives an IntentObject and returns a result string.
"""

import os
from pathlib import Path
from datetime import datetime
from core.intent_model import IntentObject


OUTPUT_DIR = Path("output")


def _ensure_output():
    OUTPUT_DIR.mkdir(exist_ok=True)


# ─────────────────────────────────────────────
# ✅ ALLOWED TOOLS
# ─────────────────────────────────────────────

def draft_document(intent: IntentObject) -> str:
    """Drafts a legal document and saves it to output/."""
    _ensure_output()
    filename = intent.target if intent.target.startswith("output/") else f"output/doc_{intent.case_id}_{datetime.now().strftime('%H%M%S')}.txt"
    Path(filename).parent.mkdir(parents=True, exist_ok=True)

    content = f"""
================================================================================
LEGAL DOCUMENT
Case ID  : {intent.case_id}
Drafted  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Drafted by: AI Legal Agent (Lead Lawyer)
================================================================================

RE: {intent.content}

To Whom It May Concern,

This legal notice is issued on behalf of our client in the matter captioned above.

{_generate_document_body(intent)}

This document has been generated by an intent-verified AI legal agent operating
within the bounds of applicable professional conduct rules.

Sincerely,
AI Legal Agent — OpenClaw x ArmorIQ Platform
================================================================================
"""
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    return f"Document created: {filename}"


def search_case_law(intent: IntentObject) -> str:
    """Searches for relevant case law and legal precedents."""
    query = intent.content
    # In production: calls a legal database API or web search
    # Simulation: returns realistic mock precedents
    mock_results = _get_mock_precedents(query)
    return f"Found {len(mock_results)} relevant precedents:\n" + "\n".join(
        f"  [{i+1}] {r}" for i, r in enumerate(mock_results)
    )


def advise_client(intent: IntentObject) -> str:
    """Generates structured legal advice for the client."""
    return (
        f"⚖️  LEGAL ADVICE (Case {intent.case_id})\n"
        f"   {intent.content}\n\n"
        f"   Important: Document all relevant incidents with timestamps, "
        f"witness names, and photographic evidence where possible. "
        f"Do not communicate with opposing parties without legal representation."
    )


def summarize_case(intent: IntentObject) -> str:
    """Summarizes the case details."""
    return f"📋 Case Summary (ID: {intent.case_id}): Case analysis complete. Key issues identified and strategy under development."


def read_case_files(intent: IntentObject) -> str:
    """Reads case files from memory (read-only, safe for delegated agents)."""
    return f"📁 Case files for {intent.case_id} retrieved. Privileged content — internal access only."


def summarize_precedents(intent: IntentObject) -> str:
    """Summarizes legal precedents found during research."""
    return f"📚 Precedent Summary: Analyzed relevant case law for query: '{intent.content}'"


# ─────────────────────────────────────────────
# 🔒 GATED TOOL (blocked by policy for direct opposing contact)
# ─────────────────────────────────────────────

def send_communication(intent: IntentObject) -> str:
    """
    Sends a communication. GATED — blocked for direct opposing party contact.
    If somehow called (policy failed), logs a critical error.
    This function should NEVER be reached for blocked intents.
    """
    # This will only execute if PolicyEngine allows it (e.g., to client's own lawyer)
    return f"Communication sent to: {intent.target} | Content: {intent.content}"


# ─────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────

def _generate_document_body(intent: IntentObject) -> str:
    content_lower = intent.content.lower()
    if "landlord" in content_lower or "illegal entry" in content_lower:
        return (
            "You are hereby notified that your unauthorized entry into the premises at "
            "[CLIENT ADDRESS] on [DATE] constitutes a violation of tenancy rights under "
            "the applicable Rent Control Act and Transfer of Property Act, 1882. "
            "You are directed to cease and desist from any further unauthorized entry "
            "and to provide written assurance of compliance within 7 days of receipt of this notice. "
            "Failure to comply will result in legal proceedings being initiated without further notice."
        )
    return (
        f"Pursuant to the matter described herein: {intent.content}. "
        "You are hereby notified of our client's legal position and rights in this matter. "
        "Please respond within the stipulated period to avoid further legal action."
    )


def _get_mock_precedents(query: str) -> list[str]:
    query_lower = query.lower()
    if "landlord" in query_lower or "entry" in query_lower or "tenant" in query_lower:
        return [
            "Satyawati v. Municipal Corporation (2018) — Unauthorized entry by landlord void under TPA",
            "Ramu Lal v. State of Delhi (2021) — Tenant rights to peaceful possession upheld",
            "Sharma Real Estate v. Gupta (2019) — Damages awarded for trespass by property owner",
        ]
    if "evidence" in query_lower or "perjury" in query_lower:
        return [
            "State v. Ramesh Kumar (2020) — Subornation of perjury IPC 191 conviction upheld",
            "CBI v. Prakash (2017) — Evidence tampering under IPC 201 cognizable offense",
        ]
    return [
        "General Legal Principle — All parties entitled to fair hearing",
        "Landmark Case on Professional Conduct (2022) — Ethical obligations of counsel",
    ]


# ─────────────────────────────────────────────
# Tool Registry (used by Executor)
# ─────────────────────────────────────────────

TOOL_REGISTRY = {
    "draft_document": draft_document,
    "search_case_law": search_case_law,
    "advise_client": advise_client,
    "summarize_case": summarize_case,
    "read_case_files": read_case_files,
    "summarize_precedents": summarize_precedents,
    "send_communication": send_communication,
}
